### PR TITLE
Update ernie dnnl benchmark

### PR DESCRIPTION
**Pull request by lidanqing-intel**
Update results with release/1.8

### CODE REVIEW

**Comment by lidanqing-intel** [comment]
@GaoWei8  Can you help rerun the failed CI? It loos random failure?

**Comment by luotao1** [comment]
@lelelelelez Could you please see the CI, this PR only change a README

**Comment by lelelelelez** [comment]
> @lelelelelez Could you please see the CI, this PR only change a README

I rerun the CI, it works. @lidanqing-intel

**Comment by lidanqing-intel** [comment]
@wojtuss  Please review.

**Pull request merged**
